---
name: "✨ Checkov - Terraform"

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - '.github/workflows/checkov.yaml'
  pull_request:
    paths:
      - 'terraform/**'
      - '.github/workflows/checkov.yaml'
  workflow_dispatch: # Allow to manually trigger the pipeline

concurrency: ci-${{ github.ref }}
jobs:
  checkov:
      name: ✨ Checkov
      runs-on: ubuntu-22.04
      steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: terraform/
          framework: terraform
          soft_fail: true
